[package]
name = "switchrs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rust-tuyapi = "0.8.2"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
toml = "0.5.9"

[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1
